modLoader = "javafml"
loaderVersion = "[1,)"
license = "${license}"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "${authors}"
description = '''${description}'''

[[mixins]]
config="${id}.mixins.json"

[[dependencies."${id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft}"
ordering = "NONE"
side = "BOTH"
